name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install libudev-dev zlib1g-dev alsa libasound2-dev
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
